#! /bin/bash

setupjl() {
    julia -q --project -E "import Pkg; Pkg.activate(\".\"); Pkg.instantiate()"
    echo "If you see something like \`command ___ not found\`, then you will have to install julia"
    echo "Otherwise, your are done!"
}

new() {
    sensible-editor "$(dirname $0)/posts/$(date +%Y-%m-%d_%H%M%S).md"
}

_tree() {
    tree $(dirname $0)/posts
}

serve() {
    PORT=$1
    HOST=$2
    [[ -z $PORT ]] && PORT=8000
    [[ -z $HOST ]] && HOST=127.0.0.1
    julia -q --project -E "using Franklin; Franklin.serve(host=\"$HOST\", port=$PORT)"
}

publish() {
    git add -A
    git commit -am "blog update $(date +%Y-%m-%d_%H%M%S).md"
    git push
}

help() {
    echo -e "Usage: blog action"
    echo -e "Actions:"
    echo -e "  new\t\t\tNew post"
    echo -e "  tree\t\t\tList posts"
    echo -e "  publish\t\tCommit and push all changes"
    echo -e "  serve [port [host]]\tBuild and serve site on host:port. Default, localhost:8081"
    echo -e "  setupjl\t\tSingle run to setup julia. Requires julia to be installed"
    echo -e "  help\t\t\tDisplay this help screen"
}

case "${1}" in
    new) new;;
    tree) _tree;;
    publish) publish;;
    serve) serve $2 $3;;
    setupjl) setupjl;;
    *) help;;
esac

